const { taste } = require('./util')

// list max levels available on server (or within your region)
const levelRestrictions = {
    campfire: 0, // all players start at 0
    hunting: 0, // all players start at 0
    butchery: -1,
    cooking: -1,
    advCooking: -1,
    baking: -1,
    advBaking: -1,
    farming: -1,
    gathering: 0, // all players start at 0
    milling: -1
};

// these are your stats, visible at the bottom left of the screen by mousing over diet pie chart
const characterStats = {
    calorieLimit: 3000, // your max calories
    // balanceBonus: 0, // for display purposes only, this gets calculated
    varietyBonus: 0, // your percentage as a whole number e.g. 25% should be 25 here
    tasteBonus: 0, // your percentage as a whole number e.g. 25% should be 25 here
    dinnerPartyBonus: 0, //WIP // your percentage as a whole number e.g. 25% should be 25 here
    cravingCount: 0, // how many cravings are satisfied
    baseGain: 12 // don't touch this, should be 12
};

const nutrition = {
    calorieMultiplier: 1, // how many sets of meals you are consuming
    avgNutrition: 0, // remove meals with nutrition average below this
    preferredOnly: false, // false to include foods you don't like
    acceptableTotal: 150, // if bonus hits this, stop searching
    maxPlates: 5, // max times you can consume a meal to reach the calorie limit
    ignoreLowFoods: false, // remove basic meals if certain Skill Levels are high
    minPreference: taste.ok // remove meals below this preference level
};

// update your preferences to help create a balanced diet while keeping taste bonus up
const myPreferences = {
    "acorn powder": taste.unassigned,
    "agave leaves": taste.unassigned,
    "agouti enchiladas": taste.unassigned,
    "autumn stew": taste.unassigned,
    "baked agave": taste.unassigned,
    "baked beet": taste.unassigned,
    "baked corn": taste.unassigned,
    "baked heart of palm": taste.unassigned,
    "baked meat": taste.unassigned,
    "baked roast": taste.unassigned,
    "baked taro": taste.unassigned,
    "baked tomato": taste.unassigned,
    "banh xeo": taste.unassigned,
    "bannock": taste.unassigned,
    "basic salad": taste.unassigned,
    "bean paste": taste.unassigned,
    "bean sprout": taste.unassigned,
    "beans": taste.unassigned,
    "bear supreme": taste.unassigned,
    "bearclaw": taste.unassigned,
    "beet campfire salad": taste.unassigned,
    "beet greens": taste.unassigned,
    "beet": taste.unassigned,
    "bison chow fun": taste.unassigned,
    "boiled grains": taste.unassigned,
    "boiled rice": taste.unassigned,
    "boiled sausage": taste.unassigned,
    "bolete": taste.unassigned,
    "bread": taste.unassigned,
    "camas bread": taste.unassigned,
    "camas bulb bake": taste.unassigned,
    "camas bulb": taste.unassigned,
    "camas paste": taste.unassigned,
    "campfire roast": taste.unassigned,
    "cereal germ": taste.unassigned,
    "charred agave": taste.unassigned,
    "charred beans": taste.unassigned,
    "charred beet": taste.unassigned,
    "charred cactus fruit": taste.unassigned,
    "charred camas bulb": taste.unassigned,
    "charred corn": taste.unassigned,
    "charred fireweed shoots": taste.unassigned,
    "charred fish": taste.unassigned,
    "charred heart of palm": taste.unassigned,
    "charred meat": taste.unassigned,
    "charred mushrooms": taste.unassigned,
    "charred papaya": taste.unassigned,
    "charred pineapple": taste.unassigned,
    "charred sausage": taste.unassigned,
    "charred taro": taste.unassigned,
    "charred tomato": taste.unassigned,
    "clam chowder": taste.unassigned,
    "cookeina": taste.unassigned,
    "corn fritters": taste.unassigned,
    "corn": taste.unassigned,
    "cornmeal": taste.unassigned,
    "cotton seed": taste.unassigned,
    "crimini": taste.unassigned,
    "crimson salad": taste.unassigned,
    "crispy bacon": taste.unassigned,
    "dried fish": taste.unassigned,
    "dried meat": taste.unassigned,
    "elk taco": taste.unassigned,
    "elk wellington": taste.unassigned,
    "fantastic forest pizza": taste.unassigned,
    "fern campfire salad": taste.unassigned,
    "fiddleheads": taste.unassigned,
    "field campfire stew": taste.unassigned,
    "fireweed shoots": taste.unassigned,
    "fish n chips": taste.unassigned,
    "flatbread": taste.unassigned,
    "flax seed": taste.unassigned,
    "flaxseed oil": taste.unassigned,
    "flour": taste.unassigned,
    "fried camas": taste.unassigned,
    "fried fiddleheads": taste.unassigned,
    "fried hare haunches": taste.unassigned,
    "fried hearts of palm": taste.unassigned,
    "fried taro": taste.unassigned,
    "fried tomatoes": taste.unassigned,
    "fruit muffin": taste.unassigned,
    "fruit salad": taste.unassigned,
    "fruit tart": taste.unassigned,
    "giant cactus fruit": taste.unassigned,
    "heart of palm": taste.unassigned,
    "heart of palm": taste.unassigned,
    "hearty hometown pizza": taste.unassigned,
    "hosomaki": taste.unassigned,
    "huckleberry extract": taste.unassigned,
    "huckleberry fritter": taste.unassigned,
    "huckleberry pie": taste.unassigned,
    "huckleberry": taste.unassigned,
    "infused oil": taste.unassigned,
    "jungle campfire salad": taste.unassigned,
    "jungle campfire stew": taste.unassigned,
    "kelpy crab roll": taste.unassigned,
    "leavened dough": taste.unassigned,
    "loaded taro fries": taste.unassigned,
    "macarons": taste.unassigned,
    "meat pie": taste.unassigned,
    "meat stock": taste.unassigned,
    "meaty stew": taste.unassigned,
    "millionaires salad": taste.unassigned,
    "mochi": taste.unassigned,
    "oil": taste.unassigned,
    "papaya": taste.unassigned,
    "pastry dough": taste.unassigned,
    "phad thai": taste.unassigned,
    "pineapple friend rice": taste.unassigned,
    "pineapple": taste.unassigned,
    "pirozhok": taste.unassigned,
    "poke bowl": taste.unassigned,
    "prepared meat": taste.unassigned,
    "prickly pear fruit": taste.unassigned,
    "prime cut": taste.unassigned,
    "pumpkin": taste.unassigned,
    "pupusas": taste.unassigned,
    "raw bacon": taste.unassigned,
    "raw fish": taste.unassigned,
    "raw meat": taste.unassigned,
    "raw roast": taste.unassigned,
    "raw sausage": taste.unassigned,
    "rice flour": taste.unassigned,
    "rice noodles": taste.unassigned,
    "rice": taste.unassigned,
    "roast pumpkin": taste.unassigned,
    "root campfire salad": taste.unassigned,
    "root campfire stew": taste.unassigned,
    "scrap meat": taste.unassigned,
    "seared meat": taste.unassigned,
    "seeded camas roll": taste.unassigned,
    "sensuous sea pizza": taste.unassigned,
    "shark fillet soup": taste.unassigned,
    "simmered meat": taste.unassigned,
    "simple syrup": taste.unassigned,
    "smooth gut noodle roll": taste.unassigned,
    "spiky roll": taste.unassigned,
    "stuffed turkey": taste.unassigned,
    "sugar": taste.unassigned,
    "sun cheese": taste.unassigned,
    "sunflower seed": taste.unassigned,
    "sunflower": taste.unassigned,
    "sweet jerky": taste.unassigned,
    "sweet salad": taste.unassigned,
    "tallow": taste.unassigned,
    "taro fries": taste.unassigned,
    "taro": taste.unassigned,
    "tasty tropical pizza": taste.unassigned,
    "tomato": taste.unassigned,
    "topped porridge": taste.unassigned,
    "torilla": taste.unassigned,
    "vegetable medley": taste.unassigned,
    "vegetable soup": taste.unassigned,
    "vegetable stock": taste.unassigned,
    "wheat": taste.unassigned,
    "wild mix": taste.unassigned,
    "wild stew": taste.unassigned,
    "wilted fiddleheads": taste.unassigned,
    "worldly donut": taste.unassigned,
    "yeast": taste.unassigned,
}

module.exports = { levelRestrictions, characterStats, nutrition, myPreferences };