const { taste, variety } = require('./util')

// list max levels available on server (or within your region)
const levelRestrictions = {
    campfire: 0, // all players start at 0
    hunting: 0, // all players start at 0
    butchery: 0,
    cooking: 0,
    advCooking: 0,
    baking: 0,
    advBaking: 0,
    farming: 0,
    gathering: 0, // all players start at 0
    milling: 0
};

// these are your stats, visible at the bottom left of the screen by mousing over diet pie chart
const characterStats = {
    calorieLimit: 3000, // your max calories
    // balanceBonus: 0, // for display purposes only, this gets calculated
    varietyBonus: 0, // your percentage as a whole number e.g. 25% should be 25 here
    tasteBonus: 0, // your percentage as a whole number e.g. 25% should be 25 here
    dinnerPartyBonus: 0, //WIP // your percentage as a whole number e.g. 25% should be 25 here
    cravingCount: 0, // how many cravings are satisfied, not percent bonuses, just count them
    baseGain: 12 // don't touch this, should be 12
};

const nutrition = {
    calorieMultiplier: 1, // how many sets of meals you are consuming
    avgNutrition: 0, // remove meals with nutrition average below this

    acceptableTotal: 150, // if bonus hits this, stop searching
    maxPlates: 5, // max times you can consume a meal to reach the calorie limit
    ignoreLowFoods: true, // remove low tier meals if certain Skill Levels are high

    preferredOnly: false, // false to include foods you don't like
    // update your preferences below
    minPreference: taste.ok // remove meals below this preference level
};

// update your preferences to help create a balanced diet while keeping taste bonus up
const myPreferences = {
    [taste.unassigned]: [
        "acorn powder",
        "agave leaves",
        "agouti enchiladas",
        "autumn stew",
        "baked agave",
        "baked beet",
        "baked corn",
        "baked heart of palm",
        "baked meat",
        "baked roast",
        "baked taro",
        "baked tomato",
        "banh xeo",
        "bannock",
        "basic salad",
        "bean paste",
        "bean sprout",
        "beans",
        "bear supreme",
        "bearclaw",
        "beet campfire salad",
        "beet greens",
        "beet",
        "bison chow fun",
        "boiled grains",
        "boiled rice",
        "boiled sausage",
        "bolete",
        "bread",
        "camas bread",
        "camas bulb bake",
        "camas bulb",
        "camas paste",
        "campfire roast",
        "cereal germ",
        "charred agave",
        "charred beans",
        "charred beet",
        "charred cactus fruit",
        "charred camas bulb",
        "charred corn",
        "charred fireweed shoots",
        "charred fish",
        "charred heart of palm",
        "charred meat",
        "charred mushrooms",
        "charred papaya",
        "charred pineapple",
        "charred sausage",
        "charred taro",
        "charred tomato",
        "clam chowder",
        "cookeina",
        "corn fritters",
        "corn",
        "cornmeal",
        "cotton seed",
        "crimini",
        "crimson salad",
        "crispy bacon",
        "dried fish",
        "dried meat",
        "elk taco",
        "elk wellington",
        "fantastic forest pizza",
        "fern campfire salad",
        "fiddleheads",
        "field campfire stew",
        "fireweed shoots",
        "fish n chips",
        "flatbread",
        "flax seed",
        "flaxseed oil",
        "flour",
        "fried camas",
        "fried fiddleheads",
        "fried hare haunches",
        "fried hearts of palm",
        "fried taro",
        "fried tomatoes",
        "fruit muffin",
        "fruit salad",
        "fruit tart",
        "giant cactus fruit",
        "heart of palm",
        "heart of palm",
        "hearty hometown pizza",
        "hosomaki",
        "huckleberry extract",
        "huckleberry fritter",
        "huckleberry pie",
        "huckleberry",
        "infused oil",
        "jungle campfire salad",
        "jungle campfire stew",
        "kelpy crab roll",
        "leavened dough",
        "loaded taro fries",
        "macarons",
        "meat pie",
        "meat stock",
        "meaty stew",
        "millionaires salad",
        "mochi",
        "oil",
        "papaya",
        "pastry dough",
        "phad thai",
        "pineapple friend rice",
        "pineapple",
        "pirozhok",
        "poke bowl",
        "prepared meat",
        "prickly pear fruit",
        "prime cut",
        "pumpkin",
        "pupusas",
        "raw bacon",
        "raw fish",
        "raw meat",
        "raw roast",
        "raw sausage",
        "rice flour",
        "rice noodles",
        "rice",
        "roast pumpkin",
        "root campfire salad",
        "root campfire stew",
        "scrap meat",
        "seared meat",
        "seeded camas roll",
        "sensuous sea pizza",
        "shark fillet soup",
        "simmered meat",
        "simple syrup",
        "smooth gut noodle roll",
        "spiky roll",
        "stuffed turkey",
        "sugar",
        "sun cheese",
        "sunflower seed",
        "sunflower",
        "sweet jerky",
        "sweet salad",
        "tallow",
        "taro fries",
        "taro",
        "tasty tropical pizza",
        "tomato",
        "topped porridge",
        "torilla",
        "vegetable medley",
        "vegetable soup",
        "vegetable stock",
        "wheat",
        "wild mix",
        "wild stew",
        "wilted fiddleheads",
        "worldly donut",
        "yeast",
    ],
    [taste.worst]: [],
    [taste.horrible]: [
    ],
    [taste.bad]: [
    ],
    [taste.ok]: [
    ],
    [taste.good]: [
    ],
    [taste.delicious]: [
    ],
    [taste.best]: []
}

const myVariety = {
    [variety.notcovered]: [
        "acorn powder",
        "agouti enchiladas",
        "autumn stew",
        "baked agave",
        "baked beet",
        "baked corn",
        "baked heart of palm",
        "baked meat",
        "baked roast",
        "baked taro",
        "baked tomato",
        "banh xeo",
        "basic salad",
        "bean paste",
        "bean sprout",
        "beans",
        "bear supreme",
        "bearclaw",
        "bison chow fun",
        "boiled rice",
        "boiled sausage",
        "bread",
        "camas bread",
        "camas bulb bake",
        "charred cactus fruit",
        "charred heart of palm",
        "clam chowder",
        "corn fritters",
        "corn",
        "cornmeal",
        "cotton seed",
        "crimini",
        "crimson salad",
        "crispy bacon",
        "dried fish",
        "dried meat",
        "elk taco",
        "elk wellington",
        "fantastic forest pizza",
        "field campfire stew",
        "fireweed shoots",
        "fish n chips",
        "flatbread",
        "flax seed",
        "flaxseed oil",
        "flour",
        "fried camas",
        "fried fiddleheads",
        "fried hare haunches",
        "fried hearts of palm",
        "fried taro",
        "fried tomatoes",
        "fruit muffin",
        "fruit salad",
        "fruit tart",
        "giant cactus fruit",
        "heart of palm",
        "heart of palm",
        "hearty hometown pizza",
        "hosomaki",
        "huckleberry extract",
        "huckleberry fritter",
        "huckleberry pie",
        "infused oil",
        "jungle campfire salad",
        "jungle campfire stew",
        "kelpy crab roll",
        "leavened dough",
        "loaded taro fries",
        "macarons",
        "meat pie",
        "meat stock",
        "meaty stew",
        "millionaires salad",
        "mochi",
        "oil",
        "pastry dough",
        "phad thai",
        "pineapple friend rice",
        "pirozhok",
        "poke bowl",
        "prepared meat",
        "prime cut",
        "pupusas",
        "raw bacon",
        "raw fish",
        "raw meat",
        "raw sausage",
        "rice noodles",
        "roast pumpkin",
        "root campfire stew",
        "scrap meat",
        "seared meat",
        "seeded camas roll",
        "sensuous sea pizza",
        "shark fillet soup",
        "simmered meat",
        "simple syrup",
        "smooth gut noodle roll",
        "spiky roll",
        "stuffed turkey",
        "sun cheese",
        "sunflower seed",
        "sunflower",
        "sweet jerky",
        "sweet salad",
        "taro fries",
        "tasty tropical pizza",
        "tomato",
        "torilla",
        "vegetable medley",
        "vegetable soup",
        "vegetable stock",
        "wheat",
        "wild mix",
        "wild stew",
        "worldly donut",
        "yeast",
    ],
    [variety.covered]: []
}

const availabity = {
    [true]: [
        "acorn powder",
        "agouti enchiladas",
        "autumn stew",
        "baked agave",
        "baked beet",
        "baked corn",
        "baked heart of palm",
        "baked meat",
        "baked roast",
        "baked taro",
        "baked tomato",
        "banh xeo",
        "basic salad",
        "bean paste",
        "bean sprout",
        "beans",
        "bear supreme",
        "bearclaw",
        "bison chow fun",
        "boiled rice",
        "boiled sausage",
        "bread",
        "camas bread",
        "camas bulb bake",
        "charred cactus fruit",
        "charred heart of palm",
        "clam chowder",
        "corn fritters",
        "corn",
        "cornmeal",
        "cotton seed",
        "crimini",
        "crimson salad",
        "crispy bacon",
        "dried fish",
        "dried meat",
        "elk taco",
        "elk wellington",
        "fantastic forest pizza",
        "field campfire stew",
        "fireweed shoots",
        "fish n chips",
        "flatbread",
        "flax seed",
        "flaxseed oil",
        "flour",
        "fried camas",
        "fried fiddleheads",
        "fried hare haunches",
        "fried hearts of palm",
        "fried taro",
        "fried tomatoes",
        "fruit muffin",
        "fruit salad",
        "fruit tart",
        "giant cactus fruit",
        "heart of palm",
        "heart of palm",
        "hearty hometown pizza",
        "hosomaki",
        "huckleberry extract",
        "huckleberry fritter",
        "huckleberry pie",
        "infused oil",
        "jungle campfire salad",
        "jungle campfire stew",
        "kelpy crab roll",
        "leavened dough",
        "loaded taro fries",
        "macarons",
        "meat pie",
        "meat stock",
        "meaty stew",
        "millionaires salad",
        "mochi",
        "oil",
        "pastry dough",
        "phad thai",
        "pineapple friend rice",
        "pirozhok",
        "poke bowl",
        "prepared meat",
        "prime cut",
        "pupusas",
        "raw bacon",
        "raw fish",
        "raw meat",
        "raw sausage",
        "rice noodles",
        "roast pumpkin",
        "root campfire stew",
        "scrap meat",
        "seared meat",
        "seeded camas roll",
        "sensuous sea pizza",
        "shark fillet soup",
        "simmered meat",
        "simple syrup",
        "smooth gut noodle roll",
        "spiky roll",
        "stuffed turkey",
        "sun cheese",
        "sunflower seed",
        "sunflower",
        "sweet jerky",
        "sweet salad",
        "taro fries",
        "tasty tropical pizza",
        "tomato",
        "torilla",
        "vegetable medley",
        "vegetable soup",
        "vegetable stock",
        "wheat",
        "wild mix",
        "wild stew",
        "worldly donut",
        "yeast",
    ],
    [false]: []
}

module.exports = {
    levelRestrictions,
    characterStats,
    nutrition,
    myPreferences,
    availabity,
};