"use strict";

// name (second column) from recipe list
let lostSources = [];

let tagList = {
    greens: ["agave", "beet greens", "fiddleheads", "fireweed shoots"],
    vegetable: ["beans", "beet", "camas bulb", "corn", "heart of palm", "taro", "tomato"],
    fruit: ["giant cactus fruit", "huckleberry", "papaya", "pineapple", "prickly pear fruit", "pumpkin"],
    grain: ["rice", "wheat"],
    fungus: ["amanita", "bolete", "cookeina", "crimini"],
    fish: ["bass", "blue shark", "clam", "cod", "crab", "moon jellyfish", "pacific sardine", "salmon", "trout", "tuna", "urchin"],
    meat: ["agouti", "alligator", "bighorn sheep", "bison", "coyote", "deer", "elk", "fox", "hare", "jaguar", "mountain goat", "otter", "prairie dog", "snapping turtle", "tortoise", "turkey", "wolf"],
    medium: ["alligator", "bighorn sheep", "deer", "elk", "jaguar", "mountain goat"],
    fat: ["flaxseed oil", "oil", "tallow"],
    oil: ["flaxseed oil", "oil"],
    _other: ["acorn", "clam", "cotton boll", "fern", "flax stem", "kelp", "oak tree", "palm log", "sunflower"],
};

// ["source", "name", level, carbs, protein, fat, vitamins, calories, [["recipe 1 a", "recipe 1 b"], ["recipe 2 a"]]],
let recipeList = [
    ["multiple", "tallow", 1, 0, 0, 8, 0, 200, [["scrap meat"], ["bison"], ["tag_medium"], ["raw bacon"]]],
    ["gathering", "heart of palm", 1, 4, 2, 0, 2, 100, [["palm log"]]],
    ["gathering", "agave leaves", 0, 2, 1, 1, 4, 200, [["agave"]]],
    ["gathering", "beans", 0, 1, 4, 3, 0, 150, [["amanita"]]],
    ["gathering", "beet", 0, 2, 0, 2, 4, 230, [["beet"]]],
    ["gathering", "beet greens", 0, 3, 1, 0, 4, 100, [["beet"]]],
    ["gathering", "bolete", 0, 2, 4, 1, 1, 200, [["bolete"]]],
    ["gathering", "camas bulb", 0, 1, 2, 5, 0, 150, [["camas bulb"]]],
    ["gathering", "cookeina", 0, 2, 4, 1, 1, 200, [["bolete"]]],
    ["gathering", "corn", 0, 4, 1, 0, 3, 230, [["corn"]]],
    ["gathering", "crimini", 0, 2, 4, 1, 1, 200, [["crimini"]]],
    ["gathering", "fiddleheads", 0, 2, 1, 0, 5, 150, [["fern"]]],
    ["gathering", "fireweed shoots", 0, 3, 1, 0, 4, 150, [["fireweed shoots"]]],
    ["gathering", "giant cactus fruit", 0, 2, 0, 2, 4, 100, [["fireweed shoots"]]],
    ["gathering", "heart of palm", 0, 4, 2, 0, 2, 100, [["fireweed shoots"]]],
    ["gathering", "huckleberry", 0, 2, 0, 0, 6, 150, [["huckleberry"]]],
    ["gathering", "papaya", 0, 2, 1, 0, 5, 200, [["papaya"]]],
    ["gathering", "pineapple", 0, 6, 0, 0, 2, 200, [["pineapple"]]],
    ["gathering", "prickly pear fruit", 0, 2, 1, 1, 4, 190, [["prickly pear fruit"]]],
    ["gathering", "pumpkin", 0, 5, 1, 0, 2, 340, [["pumpkin"]]],
    ["gathering", "rice", 0, 7, 1, 0, 0, 150, [["rice"]]],
    ["gathering", "sunflower", 0, 2, 2, 4, 0, 50, [["pumpkin"]]],
    ["gathering", "taro", 0, 6, 1, 0, 1, 250, [["pumpkin"]]],
    ["gathering", "tomato", 0, 5, 1, 0, 2, 240, [["tomato"]]],
    ["gathering", "wheat", 0, 6, 2, 0, 0, 150, [["wheat"]]],
    ["campfire", "boiled grains", 0, 9, 2, 0, 1, 350, [["tag_grain"]]],
    ["campfire", "charred agave", 0, 5, 1, 3, 3, 350, [["agave leaves"]]],
    ["campfire", "charred beans", 0, 1, 8, 3, 0, 350, [["beans"]]],
    ["campfire", "charred beet", 0, 3, 0, 3, 6, 350, [["beet"]]],
    ["campfire", "charred cactus fruit", 0, 4, 0, 2, 6, 200, [["giant cactus fruit"]]],
    ["campfire", "charred camas bulb", 0, 2, 3, 6, 1, 350, [["camas bulb"]]],
    ["campfire", "charred corn", 0, 7, 1, 0, 4, 350, [["corn"]]],
    ["campfire", "charred fireweed shoots", 0, 5, 1, 0, 6, 350, [["fireweed shoots"]]],
    ["campfire", "charred fish", 0, 0, 11, 4, 0, 400, [["tag_fish"]]],
    ["campfire", "charred heart of palm", 0, 6, 3, 1, 2, 210, [["heart of palm"]]],
    ["campfire", "charred meat", 0, 0, 5, 10, 0, 400, [["tag_meat"]]],
    ["campfire", "charred mushrooms", 0, 3, 6, 2, 1, 350, [["tag_fungus"]]],
    ["campfire", "charred papaya", 0, 3, 1, 0, 8, 350, [["papaya"]]],
    ["campfire", "charred pineapple", 0, 8, 1, 0, 3, 350, [["pineapple"]]],
    ["campfire", "charred taro", 0, 10, 1, 0, 1, 350, [["taro"]]],
    ["campfire", "charred tomato", 0, 7, 1, 0, 4, 350, [["tomato"]]],
    ["campfire", "wilted fiddleheads", 0, 4, 1, 0, 7, 350, [["fiddleheads"]]],
    ["campfire", "beet campfire salad", 1, 8, 4, 3, 13, 900, [["beet", "tag_fruit", "tag_greens"]]],
    ["campfire", "charred sausage", 1, 0, 10, 14, 0, 700, [["raw sausage"]]],
    ["campfire", "fern campfire salad", 1, 9, 5, 1, 13, 900, [["fiddleheads", "huckleberry", "tag_vegetable"]]],
    ["campfire", "jungle campfire salad", 1, 11, 4, 3, 10, 900, [["papaya", "scrap meat", "flour", "tag_fat", "tag_fungus"]]],
    ["campfire", "root campfire salad", 1, 8, 5, 4, 11, 950, [["camas bulb", "taro root", "tag_greens"]]],
    ["campfire", "topped porridge", 1, 10, 4, 0, 10, 700, [["boiled grains", "tag_fruit"]]],
    ["campfire", "bannock", 2, 15, 3, 6, 0, 700, [["wheat", "tag_fat"]]],
    ["campfire", "campfire roast", 2, 0, 16, 12, 0, 1000, [["raw roast"]]],
    ["campfire", "fried camas", 2, 9, 3, 10, 2, 700, [["camas bulb", "tag_fat"]]],
    ["campfire", "fried fiddleheads", 2, 11, 3, 6, 4, 700, [["fiddleheads", "tag_fat"]]],
    ["campfire", "fried hearts of palm", 2, 13, 3, 6, 2, 700, [["heart of palm", "tag_fat"]]],
    ["campfire", "fried taro", 2, 14, 1, 8, 1, 700, [["taro", "tag_fat"]]],
    ["campfire", "fried tomatoes", 2, 11, 3, 8, 2, 700, [["tomato", "tag_fat"]]],
    ["campfire", "meaty stew", 3, 6, 13, 10, 1, 1100, [["charred meat", "scrap meat", "flour", "tag_fat"], ["charred fish", "flour", "tag_fat"]]],
    ["campfire", "field campfire stew", 4, 14, 4, 8, 4, 1100, [["corn", "tomato", "scrap meat", "flour", "tag_fat"]]],
    ["campfire", "jungle campfire stew", 4, 8, 8, 11, 3, 1100, [["papaya", "scrap meat", "flour", "tag_fat", "tag_fungus"]]],
    ["campfire", "root campfire stew", 4, 8, 5, 12, 5, 1100, [["beet", "camas bulb", "scrap meat", "flour", "tag_fat"]]],
    ["campfire", "wild stew", 6, 10, 2, 6, 12, 1100, [["huckleberry", "beans", "beet", "flour", "tag_vegetable"]]],
    ["hunting", "raw fish", 1, 0, 7, 3, 0, 200, [["tag_fish"]]],
    ["hunting", "dried fish", 2, 1, 16, 2, 0, 450, [["raw fish"]]],
    ["hunting", "dried meat", 2, 1, 14, 4, 0, 550, [["raw meat"]]],
    ["hunting", "sweet jerky", 4, 4, 22, 6, 3, 600, [["raw meat", "sugar", "tag_oil", "tag_fruit"]]],
    ["butchery", "raw meat", 1, 0, 4, 8, 0, 25, [["tag_meat"]]],
    ["butchery", "scrap meat", 1, 0, 5, 5, 0, 50, [["raw meat"]]],
    ["butchery", "raw sausage", 2, 0, 4, 8, 0, 500, [["scrap meat"]]],
    ["butchery", "raw roast", 3, 0, 6, 5, 0, 600, [["raw meat"]]],
    ["butchery", "raw bacon", 3, 0, 3, 9, 0, 200, [["raw meat"]]],
    ["butchery", "prepared meat", 4, 0, 4, 6, 0, 600, [["raw meat"]]],
    ["butchery", "prime cut", 6, 0, 9, 4, 0, 600, [["raw meat"]]],
    ["cooking", "rice noodles", 1, 10, 0, 0, 0, 200, [["rice flour"]]],
    ["cooking", "vegetable medley", 1, 8, 4, 7, 17, 900, [["beans", "tomato", "beet"], ["corn", "camas bulb"], ["crimini", "cookeina", "bolete"]]],
    ["cooking", "fruit salad", 1, 12, 4, 3, 19, 900, [["prickly pear fruit", "pumpkin"], ["huckleberry", "beet"], ["papaya", "pineapple"]]],
    ["cooking", "basic salad", 1, 18, 6, 4, 10, 800, [["prickly pear fruit", "crimini", "rice"], ["fiddleheads", "tomato", "fireweed shoots"], ["corn", "tomato", "beet"], ["fiddleheads", "huckleberry", "beans"], ["taro", "bolete", "papaya"]]],
    ["cooking", "autumn stew", 2, 13, 8, 5, 12, 1200, [["pumpkin", "beans", "tag_greens"]]],
    ["cooking", "meat stock", 2, 3, 8, 9, 0, 600, [["scrap meat"]]],
    ["cooking", "shark fillet soup", 2, 10, 15, 11, 4, 1400, [["meat stock", "blue shark"]]],
    ["cooking", "simmered meat", 2, 6, 18, 13, 5, 900, [["prepared meat", "meat stock"]]],
    ["cooking", "crispy bacon", 3, 0, 18, 26, 0, 800, [["raw bacon"]]],
    ["cooking", "vegetable soup", 3, 12, 4, 7, 19, 1200, [["vegetable stock", "vegetable medley"]]],
    ["cooking", "taro fries", 3, 10, 2, 20, 0, 600, [["taro", "tag_oil"]]],
    ["cooking", "vegetable stock", 3, 11, 1, 2, 11, 700, [["vegetable medley"]]],
    ["cooking", "mochi", 4, 25, 0, 0, 5, 750, [["rice flour", "sugar", "cornmeal"]]],
    ["cooking", "pupusas", 4, 6, 11, 9, 14, 900, [["cornmeal", "tomato", "beans", "sun cheese"]]],
    ["cooking", "smooth gut noodle roll", 4, 19, 15, 9, 1, 1200, [["rice noodles", "prepared meat", "tag_oil"]]],
    ["cooking", "clam chowder", 5, 16, 15, 3, 11, 800, [["clam", "taro"]]],
    ["cooking", "loaded taro fries", 5, 14, 6, 18, 0, 1200, [["taro fries", "sun cheese", "prepared meat"]]],
    ["cooking", "phad thai", 6, 9, 11, 19, 5, 1200, [["rice noodles", "prepared meat", "bean sprout", "sugar", "acorn", "tag_oil"]]],
    ["advCooking", "boiled rice", 1, 13, 2, 0, 0, 210, [["rice"]]],
    ["advCooking", "corn fritters", 1, 13, 4, 22, 8, 500, [["cornmeal", "corn", "tag_fat"]]],
    ["advCooking", "fish n chips", 1, 20, 10, 20, 0, 1000, [["raw fish", "taro fries", "flour", "tag_oil"]]],
    ["advCooking", "infused oil", 1, 0, 0, 12, 3, 120, [["huckleberry extract", "tag_oil"]]],
    ["advCooking", "seared meat", 1, 4, 19, 17, 7, 600, [["prime cut", "infused oil"]]],
    ["advCooking", "wild mix", 1, 15, 6, 4, 21, 800, [["basic salad", "huckleberry extract"]]],
    ["advCooking", "boiled sausage", 2, 0, 27, 22, 0, 600, [["raw sausage", "meat stock"]]],
    ["advCooking", "fried hare haunches", 2, 6, 15, 27, 4, 750, [["flour", "prepared meat", "tag_oil"]]],
    ["advCooking", "torilla", 2, 20, 10, 0, 0, 350, [["cornmeal"]]],
    ["advCooking", "elk taco", 2, 15, 8, 22, 6, 700, [["scrap meat", "tortilla", "wild mix"]]],
    ["advCooking", "crimson salad", 3, 13, 7, 8, 28, 1200, [["basic salad", "infused oil", "charred beet", "tomato"]]],
    ["advCooking", "hosomaki", 3, 21, 19, 5, 8, 700, [["boiled rice", "kelp", "raw fish"]]],
    ["advCooking", "kelpy crab roll", 3, 22, 13, 11, 5, 1350, [["boiled rice", "kelp", "crab"]]],
    ["advCooking", "seeded camas roll", 3, 20, 2, 13, 16, 1400, [["boiled rice", "kelp", "camas paste", "fiddleheads"]]],
    ["advCooking", "sweet salad", 3, 18, 9, 7, 22, 1200, [["basic salad", "fruit salad", "simple syrup"]]],
    ["advCooking", "spiky roll", 3, 20, 17, 7, 2, 1300, [["boiled rice", "urchin"]]],
    ["advCooking", "agouti enchiladas", 4, 20, 8, 27, 3, 800, [["cornmeal", "tomato", "papaya", "sun cheese", "prime cut"]]],
    ["advCooking", "bison chow fun", 4, 16, 13, 20, 8, 1450, [["rice noodles", "bean sprout", "bison", "tag_oil"]]],
    ["advCooking", "poke bowl", 4, 21, 10, 11, 7, 1100, [["boiled rice", "beans", "kelp", "tuna"]]],
    ["advCooking", "banh xeo", 4, 26, 17, 10, 4, 1550, [["rice flour", "prime cut", "bean sprout", "crab", "tag_oil"]]],
    ["advCooking", "pineapple friend rice", 5, 20, 9, 12, 12, 720, [["charred pineapple", "boiled rice", "scrap meat"]]],
    ["advCooking", "bear supreme", 6, 6, 22, 23, 9, 1250, [["prime cut", "vegetable medley", "meat stock", "infused oil"]]],
    ["advCooking", "millionaires salad", 6, 18, 6, 6, 26, 1000, [["heart of palm", "cookeina", "papaya", "pineapple"]]],
    ["baking", "baked agave", 1, 14, 2, 4, 8, 700, [["agave leaves"]]],
    ["baking", "baked beet", 1, 10, 1, 2, 15, 700, [["beet"]]],
    ["baking", "baked corn", 1, 12, 3, 2, 11, 700, [["corn"]]],
    ["baking", "baked heart of palm", 1, 12, 6, 4, 6, 700, [["heart of palm"]]],
    ["baking", "baked meat", 1, 0, 17, 13, 0, 700, [["raw meat"]]],
    ["baking", "baked roast", 3, 4, 16, 10, 4, 1000, [["raw roast"]]],
    ["baking", "baked taro", 1, 8, 6, 2, 12, 700, [["taro"]]],
    ["baking", "baked tomato", 1, 16, 1, 5, 6, 700, [["tomato"]]],
    ["baking", "camas bulb bake", 1, 12, 7, 5, 4, 700, [["camas bulb"]]],
    ["baking", "flatbread", 1, 17, 8, 3, 2, 500, [["flour"]]],
    ["baking", "leavened dough", 1, 6, 18, 13, 5, 10, [["flour", "yeast"]]],
    ["baking", "pastry dough", 1, 4, 0, 0, 4, 10, [["flour", "yeast", "tag_fat"]]],
    ["baking", "fruit muffin", 2, 10, 5, 4, 16, 800, [["flour", "tag_fruit"]]],
    ["baking", "roast pumpkin", 3, 23, 2, 2, 7, 1400, [["pumpkin", "sugar"]]],
    ["baking", "bread", 4, 23, 6, 4, 2, 750, [["leavened dough"]]],
    ["baking", "worldly donut", 4, 15, 2, 17, 2, 750, [["sugar", "pastry dough", "tag_oil"]]],
    ["baking", "camas bread", 5, 13, 5, 11, 7, 800, [["camas paste", "leavened dough"]]],
    ["baking", "huckleberry fritter", 5, 16, 0, 20, 8, 900, [["sugar", "pastry dough", "huckleberry extract", "tag_oil"]]],
    ["baking", "huckleberry pie", 5, 13, 5, 10, 16, 1300, [["flour", "huckleberry", "tag_fat"]]],
    ["baking", "meat pie", 5, 18, 4, 20, 2, 1300, [["flour", "scrap meat", "tag_fat"]]],
    ["advBaking", "fruit tart", 1, 22, 3, 9, 14, 800, [["pastry dough", "tag_fruit"]]],
    ["advBaking", "pirozhok", 1, 14, 19, 10, 4, 850, [["pastry dough", "prepared meat", "tag_fungus"]]],
    ["advBaking", "bearclaw", 2, 14, 4, 21, 7, 850, [["pastry dough", "sugar"]]],
    ["advBaking", "hearty hometown pizza", 3, 28, 7, 11, 3, 1200, [["leavened dough", "crimini", "raw sausage", "sun cheese", "tomato"]]],
    ["advBaking", "tasty tropical pizza", 3, 21, 6, 12, 11, 1200, [["leavened dough", "raw bacon", "pineapple", "sun cheese", "tomato"]]],
    ["advBaking", "sensuous sea pizza", 3, 28, 11, 7, 4, 1200, [["leavened dough", "raw fish", "kelp", "sun cheese", "tomato"]]],
    ["advBaking", "fantastic forest pizza", 3, 23, 4, 10, 17, 1250, [["leavened dough", "camas bulb", "sun cheese", "tomato", "tag_greens"]]],
    ["advBaking", "stuffed turkey", 4, 17, 24, 16, 7, 1600, [["prime cut", "bread", "vegetable medley"]]],
    ["advBaking", "macarons", 5, 20, 7, 14, 16, 1000, [["pastry dough", "sugar", "huckleberry extract"]]],
    ["advBaking", "elk wellington", 6, 10, 26, 22, 4, 1450, [["leavened dough", "prime cut"]]],
    ["farming", "bean sprout", 1, 2, 1, 0, 5, 100, [["beans"]]],
    ["farming", "cotton seed", 1, 0, 0, 0, 0, 0, [["cotton boll"]]],
    ["farming", "flax seed", 1, 0, 0, 0, 0, 0, [["flax stem"]]],
    ["farming", "sunflower seed", 1, 0, 0, 0, 0, 0, [["sunflower"]]],
    ["milling", "cereal germ", 1, 5, 0, 7, 3, 20, [["corn"], ["wheat"], ["rice"]]],
    ["milling", "cornmeal", 1, 9, 3, 3, 0, 60, [["corn"]]],
    ["milling", "flour", 1, 15, 0, 0, 0, 50, [["wheat"]]],
    ["milling", "rice flour", 1, 15, 0, 0, 0, 50, [["rice"]]],
    ["milling", "sugar", 1, 15, 0, 0, 0, 50, [["beet"], ["huckleberry"]]],
    ["milling", "oil", 1, 0, 0, 15, 0, 120, [["cotton seed"], ["cereal germ"], ["sunflower seed"], ["tallow"]]],
    ["milling", "camas paste", 2, 3, 2, 10, 0, 60, [["camas bulb"]]],
    ["milling", "huckleberry extract", 2, 0, 0, 0, 15, 60, [["huckleberry"]]],
    ["milling", "simple syrup", 2, 12, 0, 3, 0, 400, [["sugar"]]],
    ["milling", "bean paste", 3, 3, 5, 7, 0, 40, [["beans"]]],
    ["milling", "flaxseed oil", 3, 0, 0, 15, 0, 120, [["flax seed"]]],
    ["milling", "sun cheese", 3, 2, 4, 12, 0, 250, [["sunflower seed", "yeast", "rice", "tag_oil"]]],
    ["milling", "yeast", 4, 0, 8, 0, 7, 60, [["sugar"]]],
    ["milling", "acorn powder", 5, 1, 5, 2, 5, 40, [["acorn"]]],
];

module.exports = {
    lostSources,
    tagList,
    recipeList,
};